// Shared test fixtures: string constants for URLs, auth headers and
// repeated literals (S-126 / S1192). Kept in one file so every
// httpapi test file shares a single source of truth.

package httpapi

const (
	aliceEmail                = "alice@example.com"
	authAdmin                 = "Bearer admin"
	authAlice                 = "Bearer alice"
	authOwner                 = "Bearer owner"
	authViewer                = "Bearer viewer"
	cascadeKeyConvergedAction = "aimodel.cascade.key_converged"
	deadProviderName          = "Dead Provider"
	forceQuery                = "?force=true"
	legacyFieldValue          = "ignored-legacy-field"
	localFastModel            = "openai/local-fast"
	localLLMBaseURL           = "http://localhost:8123/v1"
	modelOne                  = "openai/one"
	modelTwo                  = "openai/two"
	pathAIModelItem           = "/api/v1/ai-models/"
	pathAIModels              = "/api/v1/ai-models"
	pathAgentsPrefix          = "/api/v1/agents/"
	pathAuthMe                = "/api/v1/auth/me"
	pathDashboard             = "/api/v1/dashboard"
	pathDeprecate             = "/deprecate"
	pathIdentity              = "/identity"
	pathModels                = "/models"
	pathModelsSlash           = "/models/"
	pathMyModels              = "/api/v1/models/me"
	pathPermissions           = "/permissions"
	pathProvidersPrefix       = "/api/v1/registry/llm-providers/"
	pathSquadsPrefix          = "/api/v1/squads/"
	pathUsersPrefix           = "/api/v1/users/"
	sharedModelName           = "shared-name"
	statusInProgress          = "in-progress"
	testIssuer                = "https://issuer.example.com"
	adminEmail                = "admin@example.com"
	authReader                = "Bearer reader"
	authUser                  = "Bearer user"
	bearerPrefix              = "Bearer "
	callbackToken             = "callback-token"
	durableSummary            = "Durable completion summary"
	gitSecretRef              = "secret/git/x"
	headerContentType         = "Content-Type"
	jsonContentType           = "application/json"
	openaiCompatible          = "openai-compatible"
	pathAccessGrants          = "/access-grants"
	pathAgents                = "/agents"
	pathAudit                 = "/audit"
	pathBlock                 = "/block"
	pathBoard                 = "/board"
	pathBoardTasks            = "/board/tasks"
	pathBreakglassLogin       = "/api/v1/auth/breakglass/login"
	pathComplete              = "/complete"
	pathGatewayKeysReconcile  = "/api/v1/admin/gateway/keys/reconcile"
	pathInbox                 = "/api/v1/inbox"
	pathMessages              = "/messages"
	pathMetering              = "/metering"
	pathMyHeartbeat           = "/api/v1/agents/me/heartbeat"
	pathMyMessages            = "/api/v1/agents/me/messages"
	pathMyMessagesPrefix      = "/api/v1/agents/me/messages/"
	pathMyTasks               = "/api/v1/agents/me/tasks"
	pathMyTasksClaim          = "/api/v1/agents/me/tasks/claim"
	pathMyTasksPrefix         = "/api/v1/agents/me/tasks/"
	pathProviders             = "/api/v1/registry/llm-providers"
	pathSkills                = "/api/v1/registry/skills"
	pathSkillsPrefix          = "/api/v1/registry/skills/"
	pathSquads                = "/api/v1/squads"
	pathTaskMissing           = "/api/v1/tasks/does-not-exist"
	pathTasksPrefix           = "/api/v1/tasks/"
	pathWorkspace             = "/workspace"
	platformAdminGroup        = "ross-private-cloud:platform"
	remoteAddrCGNAT           = "100.64.9.9:5555"
	remoteAddrLAN             = "192.168.68.5:1234"
	testRepoURL               = "https://git.example.com/team/repo.git"
	unsupportedHandoff        = "unsupported handoff"
)
