{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skquad.webName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      {{- include "skquad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "skquad.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: {{ include "skquad.webImage" . | quote }}
          imagePullPolicy: {{ .Values.web.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            - name: SKQUAD_API_BASE_URL
              value: {{ printf "http://%s.%s.svc.cluster.local/api/v1" (include "skquad.apiServerName" .) .Release.Namespace | quote }}
            - name: NEXT_PUBLIC_SKQUAD_API_BASE_URL
              value: {{ .Values.web.apiBaseUrl | quote }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
